# GitHub
username:             vborza
repo:                 vborza.github.io
branch:               source

# Google services
google_analytics: UA-89496232-1
include_analytics: true

# Site settings
url: https://borza.dev
date_format: "%-d %B %Y"
excerpt_separator: <!--more-->
# Jekyll source / destination
#source:               .
#destination:          _site

gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]
paginate: 15
paginate_path: "/blog/page:num/"

exclude: [vendor]

show_drafts: false

#seo
title: borza.dev 
description: Personal blog dedicated to programming, software architecture and cutting edge trends in IT world.
author:
  twitter: vicBorza
twitter:
  username: vicBorza
social:
  name: Viktor Borza
  links:
    - https://www.linkedin.com/in/vborza
    - https://twitter.com/vicBorza
    - https://www.facebook.com/viktor.borza
    - https://github.com/vborza
